# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9faf1def6eed90e064ea46e4712deba636dc42e9c82413445f1d3d16f9d3d5daed300e3ecd0007c9b4b54fca0e5733280a6e3d2db723a463ecfa85de379c3fd

test:
  secret_key_base: 6571197a1b3d2a05426deddd2e2dbccd46c992b2bb8c4f43496488292bf955d5f3aa2895960ccf258aaa2fe29e79856d44dc9be0948ce23ab87d372561e0d938

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
